name: mylocca_mobile
description: Application mobile Flutter pour les locataires - MyLocca
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP client pour les appels API
  http: ^1.1.0

  # Gestion de l'état
  provider: ^6.1.1

  # Stockage local (token, préférences)
  shared_preferences: ^2.2.2

  # UI
  cupertino_icons: ^1.0.6

  # Routing
  go_router: ^12.1.3

  # JSON serialization
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

