# config/packages/messenger.yaml - Configuration Production MySQL 8
framework:
    messenger:
        # Transport pour les messages échoués
        failure_transport: failed

        transports:
            # Transport async optimisé pour MySQL 8
            async:
                dsn: 'doctrine://default?auto_setup=0'
                options:
                    table_name: messenger_messages
                    queue_name: async
                    redeliver_timeout: 3600
                    check_delayed_interval: 60
                    get_notify_timeout: 5

            # Transport pour les messages échoués
            failed:
                dsn: 'doctrine://default?queue_name=failed'

            # Transport synchrone (pour les tests)
            sync: 'sync://'

        routing:
            # Route your messages to the transports
            # Configuration optimisée pour MySQL 8.0+ (production)
            'App\Message\GenerateRentsMessage': async
            'App\Message\GenerateRentDocumentsMessage': async
            'App\Message\SendRentReceiptsMessage': async
            'App\Message\SendPaymentRemindersMessage': async
            'App\Message\SendLeaseExpirationAlertsMessage': async
            'App\Message\SyncAccountingEntriesMessage': async
            'App\Message\UpdatePropertyStatusMessage': async
            'App\Message\CleanupDemoEnvironmentsMessage': async
            'App\Message\CreateSuperAdminMessage': async
            'App\Message\AuditCleanupMessage': async
            'App\Message\BackupMessage': async
            'App\Message\TestEmailConfigMessage': async
            'App\Message\FixUserOrganizationMessage': async
            'App\Message\DemoCreateMessage': async
            'App\Message\CreateAccountingConfigurationsMessage': async
            'App\Message\TestAccountingConfigMessage': async
            'App\Message\CheckAccountingEntriesMessage': async
            'App\Message\TestRentGenerationWithConfigMessage': async
            'App\Message\DemoAccountingSystemMessage': async
            'App\Message\FixAccountingTableMessage': async
            'App\Message\SetupAccountingSystemMessage': async
            'App\Message\InitializeEmailSettingsMessage': async
            'App\Message\TestEmailSettingsMessage': async
            'App\Message\TestSmtpConfigurationMessage': async
            'App\Message\UpdateSmtpConfigurationMessage': async
