nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']  # Autoriser toutes les origines (à restreindre en production)
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-User-Email']  # Ajouter X-User-Email
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/':  # Appliquer CORS uniquement aux routes API
            allow_origin: ['*']
            allow_headers: ['Content-Type', 'Authorization', 'X-User-Email']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS']
            max_age: 3600
