# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    documents_directory: '%kernel.project_dir%/public/uploads/documents'
    # Mapping des clés de chiffrement depuis les variables d'environnement
    # Permet d'utiliser %app.encryption_key% dans la configuration/services si nécessaire
    app.encryption_key: '%env(APP_ENCRYPTION_KEY)%'
    app.documents_encryption_key: '%env(APP_DOCUMENTS_ENCRYPTION_KEY)%'
    app.legacy_documents_encryption_key: '%env(APP_LEGACY_DOCUMENTS_ENCRYPTION_KEY)%'

    # Configuration cPanel API
    cpanel.host: '%env(CPANEL_HOST)%'
    cpanel.username: '%env(CPANEL_USERNAME)%'
    cpanel.token: '%env(CPANEL_API_TOKEN)%'
    cpanel.port: '%env(int:CPANEL_PORT)%'
    cpanel.demo_domain: '%env(CPANEL_DEMO_DOMAIN)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\ContractGenerationService:
        arguments:
            $documentsDirectory: '%documents_directory%'

    # Service pour gérer les dumps de base de données
    App\Service\DatabaseDumpService:
        arguments:
            $projectDir: '%kernel.project_dir%'

    # Service cPanel API pour gestion des environnements de démo
    App\Service\CpanelApiService:
        arguments:
            $cpanelHost: '%cpanel.host%'
            $cpanelUsername: '%cpanel.username%'
            $cpanelToken: '%cpanel.token%'
            $cpanelPort: '%cpanel.port%'

    # Enregistrement du processeur d'environnement pour Orange SMS
    App\Service\OrangeSmsEnvironmentVariableProcessor:
        tags: ['container.env_var_processor']

    # EventListener pour la mise à jour automatique du statut des propriétés
    App\EventListener\PropertyStatusListener:
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postRemove }
